### ISSUE TITLE
Improve the sort order in the context menu

### ISSUE THREAD

**Issue by egamma** [chrisdias/vscode-opennewinstance#1]
Since 1.4 you have control over the sort order of the menus, see Sorting of Groups in https://code.visualstudio.com/Updates#_extension-authoring.

I suggest that these actions appear at the bottom of the navigation group, e.g.,

```json
		"menus": {
			"explorer/context": [
				{
					...
					"group": "navigation@+1"
				}
			]
		},
```

**Comment by chrisdias** [comment]
fixed

![image](https://cloud.githubusercontent.com/assets/1487073/18294822/0203674a-7451-11e6-8b50-ce137736b226.png)
