### ISSUE TITLE
Appear below built-in context menu options

### ISSUE THREAD

**Issue by bkromhout** [chrisdias/vscode-opennewinstance#10]
In VS Code 1.50.1 on Windows 10, it appears that the context menu items that this extension adds are once again appearing above the built-in options rather than below them, as can be seen from the following screenshot.

![image](https://user-images.githubusercontent.com/4447359/98002684-cff59480-1dbb-11eb-80ac-da6df0f78940.png)

Can this be fixed to move them back below the built-in items please?

**Comment by inwardmovement** [comment]
Same here, I'll be glad to have them back below the built-in items.

**Comment by chrisdias** [comment]
fixed with #11
