### ISSUE TITLE
Add when clause to "Reopen Workbench Here"

### ISSUE THREAD

**Issue by Denis-net** [chrisdias/vscode-opennewinstance#7]
Hey @chrisdias !
Nice extension, just one thing:
could you add this
```JSON
"when": "explorerResourceIsFolder"
```
to your `extension.scopeToHere` command in the `menu \ explorer/context` section ?
And set the commandPalette visibility to never ?
This would improve the UX.
Best !

**Comment by chrisdias** [comment]
good idea, working on it.
